package algo

import (
	"strings"

	"github.com/mozillazg/go-pinyin"
)

var (
	PinyinSeparator = " "
)

// 全拼 -> 微软双拼
var MSPY = map[string]string{
	"a":      "oa",
	"ai":     "ol",
	"an":     "oj",
	"ang":    "oh",
	"ao":     "ok",
	"ba":     "ba",
	"bai":    "bl",
	"ban":    "bj",
	"bang":   "bh",
	"bao":    "bk",
	"bei":    "bz",
	"ben":    "bf",
	"beng":   "bg",
	"bi":     "bi",
	"bian":   "bm",
	"biang":  "bd",
	"biao":   "bc",
	"bie":    "bx",
	"bin":    "bn",
	"bing":   "b;",
	"bo":     "bo",
	"bu":     "bu",
	"ca":     "ca",
	"cai":    "cl",
	"can":    "cj",
	"cang":   "ch",
	"cao":    "ck",
	"ce":     "ce",
	"cei":    "cz",
	"cen":    "cf",
	"ceng":   "cg",
	"cha":    "ia",
	"chai":   "il",
	"chan":   "ij",
	"chang":  "ih",
	"chao":   "ik",
	"che":    "ie",
	"chen":   "if",
	"cheng":  "ig",
	"chi":    "ii",
	"chong":  "is",
	"chou":   "ib",
	"chu":    "iu",
	"chua":   "iw",
	"chuai":  "iy",
	"chuan":  "ir",
	"chuang": "id",
	"chui":   "iv",
	"chun":   "ip",
	"chuo":   "io",
	"ci":     "ci",
	"cong":   "cs",
	"cou":    "cb",
	"cu":     "cu",
	"cuan":   "cr",
	"cui":    "cv",
	"cun":    "cp",
	"cuo":    "co",
	"da":     "da",
	"dai":    "dl",
	"dan":    "dj",
	"dang":   "dh",
	"dao":    "dk",
	"de":     "de",
	"dei":    "dz",
	"den":    "df",
	"deng":   "dg",
	"di":     "di",
	"dia":    "dw",
	"dian":   "dm",
	"diao":   "dc",
	"die":    "dx",
	"din":    "dn",
	"ding":   "d;",
	"diu":    "dq",
	"dong":   "ds",
	"dou":    "db",
	"du":     "du",
	"duan":   "dr",
	"dui":    "dv",
	"dun":    "dp",
	"duo":    "do",
	"e":      "oe",
	"ei":     "oz",
	"en":     "of",
	"eng":    "og",
	"er":     "or",
	"fa":     "fa",
	"fan":    "fj",
	"fang":   "fh",
	"fei":    "fz",
	"fen":    "ff",
	"feng":   "fg",
	"fiao":   "fc",
	"fo":     "fo",
	"fou":    "fb",
	"fu":     "fu",
	"ga":     "ga",
	"gai":    "gl",
	"gan":    "gj",
	"gang":   "gh",
	"gao":    "gk",
	"ge":     "ge",
	"gei":    "gz",
	"gen":    "gf",
	"geng":   "gg",
	"gong":   "gs",
	"gou":    "gb",
	"gu":     "gu",
	"gua":    "gw",
	"guai":   "gy",
	"guan":   "gr",
	"guang":  "gd",
	"gui":    "gv",
	"gun":    "gp",
	"guo":    "go",
	"ha":     "ha",
	"hai":    "hl",
	"han":    "hj",
	"hang":   "hh",
	"hao":    "hk",
	"he":     "he",
	"hei":    "hz",
	"hen":    "hf",
	"heng":   "hg",
	"hong":   "hs",
	"hou":    "hb",
	"hu":     "hu",
	"hua":    "hw",
	"huai":   "hy",
	"huan":   "hr",
	"huang":  "hd",
	"hui":    "hv",
	"hun":    "hp",
	"huo":    "ho",
	"ji":     "ji",
	"jia":    "jw",
	"jian":   "jm",
	"jiang":  "jd",
	"jiao":   "jc",
	"jie":    "jx",
	"jin":    "jn",
	"jing":   "j;",
	"jiong":  "js",
	"jiu":    "jq",
	"ju":     "ju",
	"juan":   "jr",
	"jue":    "jv",
	"jun":    "jp",
	"ka":     "ka",
	"kai":    "kl",
	"kan":    "kj",
	"kang":   "kh",
	"kao":    "kk",
	"ke":     "ke",
	"kei":    "kz",
	"ken":    "kf",
	"keng":   "kg",
	"kong":   "ks",
	"kou":    "kb",
	"ku":     "ku",
	"kua":    "kw",
	"kuai":   "ky",
	"kuan":   "kr",
	"kuang":  "kd",
	"kui":    "kv",
	"kun":    "kp",
	"kuo":    "ko",
	"la":     "la",
	"lai":    "ll",
	"lan":    "lj",
	"lang":   "lh",
	"lao":    "lk",
	"le":     "le",
	"lei":    "lz",
	"len":    "lf",
	"leng":   "lg",
	"li":     "li",
	"lia":    "lw",
	"lian":   "lm",
	"liang":  "ld",
	"liao":   "lc",
	"lie":    "lx",
	"lin":    "ln",
	"ling":   "l;",
	"liu":    "lq",
	"lo":     "lo",
	"long":   "ls",
	"lou":    "lb",
	"lu":     "lu",
	"luan":   "lr",
	"lun":    "lp",
	"luo":    "lo",
	"lv":     "ly",
	"lve":    "lt",
	"ma":     "ma",
	"mai":    "ml",
	"man":    "mj",
	"mang":   "mh",
	"mao":    "mk",
	"me":     "me",
	"mei":    "mz",
	"men":    "mf",
	"meng":   "mg",
	"mi":     "mi",
	"mian":   "mm",
	"miao":   "mc",
	"mie":    "mx",
	"min":    "mn",
	"ming":   "m;",
	"miu":    "mq",
	"mo":     "mo",
	"mou":    "mb",
	"mu":     "mu",
	"na":     "na",
	"nai":    "nl",
	"nan":    "nj",
	"nang":   "nh",
	"nao":    "nk",
	"ne":     "ne",
	"nei":    "nz",
	"nen":    "nf",
	"neng":   "ng",
	"ni":     "ni",
	"nia":    "nw",
	"nian":   "nm",
	"niang":  "nd",
	"niao":   "nc",
	"nie":    "nx",
	"nin":    "nn",
	"ning":   "n;",
	"niu":    "nq",
	"nong":   "ns",
	"nou":    "nb",
	"nu":     "nu",
	"nuan":   "nr",
	"nun":    "np",
	"nuo":    "no",
	"nv":     "ny",
	"nve":    "nt",
	"o":      "oo",
	"ou":     "ob",
	"pa":     "pa",
	"pai":    "pl",
	"pan":    "pj",
	"pang":   "ph",
	"pao":    "pk",
	"pei":    "pz",
	"pen":    "pf",
	"peng":   "pg",
	"pi":     "pi",
	"pian":   "pm",
	"piao":   "pc",
	"pie":    "px",
	"pin":    "pn",
	"ping":   "p;",
	"po":     "po",
	"pou":    "pb",
	"pu":     "pu",
	"qi":     "qi",
	"qia":    "qw",
	"qian":   "qm",
	"qiang":  "qd",
	"qiao":   "qc",
	"qie":    "qx",
	"qin":    "qn",
	"qing":   "q;",
	"qiong":  "qs",
	"qiu":    "qq",
	"qu":     "qu",
	"quan":   "qr",
	"que":    "qv",
	"qun":    "qp",
	"ran":    "rj",
	"rang":   "rh",
	"rao":    "rk",
	"re":     "re",
	"ren":    "rf",
	"reng":   "rg",
	"ri":     "ri",
	"rong":   "rs",
	"rou":    "rb",
	"ru":     "ru",
	"rua":    "rw",
	"ruan":   "rr",
	"rui":    "rv",
	"run":    "rp",
	"ruo":    "ro",
	"sa":     "sa",
	"sai":    "sl",
	"san":    "sj",
	"sang":   "sh",
	"sao":    "sk",
	"se":     "se",
	"sen":    "sf",
	"seng":   "sg",
	"sha":    "ua",
	"shai":   "ul",
	"shan":   "uj",
	"shang":  "uh",
	"shao":   "uk",
	"she":    "ue",
	"shei":   "uz",
	"shen":   "uf",
	"sheng":  "ug",
	"shi":    "ui",
	"shou":   "ub",
	"shu":    "uu",
	"shua":   "uw",
	"shuai":  "uy",
	"shuan":  "ur",
	"shuang": "ud",
	"shui":   "uv",
	"shun":   "up",
	"shuo":   "uo",
	"si":     "si",
	"song":   "ss",
	"sou":    "sb",
	"su":     "su",
	"suan":   "sr",
	"sui":    "sv",
	"sun":    "sp",
	"suo":    "so",
	"ta":     "ta",
	"tai":    "tl",
	"tan":    "tj",
	"tang":   "th",
	"tao":    "tk",
	"te":     "te",
	"tei":    "tz",
	"teng":   "tg",
	"ti":     "ti",
	"tian":   "tm",
	"tiao":   "tc",
	"tie":    "tx",
	"ting":   "t;",
	"tong":   "ts",
	"tou":    "tb",
	"tu":     "tu",
	"tuan":   "tr",
	"tui":    "tv",
	"tun":    "tp",
	"tuo":    "to",
	"wa":     "wa",
	"wai":    "wl",
	"wan":    "wj",
	"wang":   "wh",
	"wei":    "wz",
	"wen":    "wf",
	"weng":   "wg",
	"wo":     "wo",
	"wong":   "ws",
	"wu":     "wu",
	"xi":     "xi",
	"xia":    "xw",
	"xian":   "xm",
	"xiang":  "xd",
	"xiao":   "xc",
	"xie":    "xx",
	"xin":    "xn",
	"xing":   "x;",
	"xiong":  "xs",
	"xiu":    "xq",
	"xu":     "xu",
	"xuan":   "xr",
	"xue":    "xv",
	"xun":    "xp",
	"ya":     "ya",
	"yan":    "yj",
	"yang":   "yh",
	"yao":    "yk",
	"ye":     "ye",
	"yi":     "yi",
	"yin":    "yn",
	"ying":   "y;",
	"yo":     "yo",
	"yong":   "ys",
	"you":    "yb",
	"yu":     "yu",
	"yuan":   "yr",
	"yue":    "yv",
	"yun":    "yp",
	"za":     "za",
	"zai":    "zl",
	"zan":    "zj",
	"zang":   "zh",
	"zao":    "zk",
	"ze":     "ze",
	"zei":    "zz",
	"zen":    "zf",
	"zeng":   "zg",
	"zha":    "va",
	"zhai":   "vl",
	"zhan":   "vj",
	"zhang":  "vh",
	"zhao":   "vk",
	"zhe":    "ve",
	"zhei":   "vz",
	"zhen":   "vf",
	"zheng":  "vg",
	"zhi":    "vi",
	"zhong":  "vs",
	"zhou":   "vb",
	"zhu":    "vu",
	"zhua":   "vw",
	"zhuai":  "vy",
	"zhuan":  "vr",
	"zhuang": "vd",
	"zhui":   "vv",
	"zhun":   "vp",
	"zhuo":   "vo",
	"zi":     "zi",
	"zong":   "zs",
	"zou":    "zb",
	"zu":     "zu",
	"zuan":   "zr",
	"zui":    "zv",
	"zun":    "zp",
	"zuo":    "zo",
}

func PinyinRemoveDuplicates(slice []string) []string {
	encountered := map[string]bool{}
	result := []string{}
	for _, str := range slice {
		if !encountered[str] {
			encountered[str] = true

			// 全拼
			// result = append(result, str)

			// 微软双拼
			if v, ok := MSPY[str]; ok {
				result = append(result, v)
			}

			// 微软双拼 - 模糊拼音
			if strings.HasSuffix(str, "in") || strings.HasSuffix(str, "en") {
				tmp := str + "g"
				if v, ok := MSPY[tmp]; ok {
					result = append(result, v)
				}
			}
			if strings.HasSuffix(str, "ing") || strings.HasSuffix(str, "eng") {
				tmp := str[:len(str)-1]
				if v, ok := MSPY[tmp]; ok {
					result = append(result, v)
				}
			}
		}
	}
	return result
}

func PinyinMod(hans string) string {
	args := pinyin.NewArgs()
	args.Heteronym = true
	slice := pinyin.Pinyin(hans, args)
	joined := make([]string, len(slice))
	for i, s := range slice {
		joined[i] = strings.Join(PinyinRemoveDuplicates(s), " ")
	}
	str := strings.Join(joined, " ")
	if str != "" {
		return PinyinSeparator + str
	} else {
		return ""
	}
}
